config/routes.rb
Rails.application.routes.draw do
  get 'svg_parsers/test_garbage'
  get 'svg_parsers/download_full_res_quilt'
  get 'svg_parsers/download_full_res_quilt_svg'
  get 'svg_parsers/download_full_res_quilt_png'

  get 'quilts/welcome'
  post 'quilts/welcome'

  get 'quilts/choose_block'
  post 'quilts/choose_block'

  get 'project_templates/choose_project'
  post 'project_templates/choose_project'

  get 'quilts/edit_project'
  post 'quilts/edit_project'

  get 'quilts/preview_project'
  post 'quilts/preview_project'

  get 'quilts/next_steps'
  post 'quilts/next_steps'
  patch 'quilts/next_steps'

  get 'quilts/download_quilt'

  resources 'quilts', :only => [:new, :create]
  get 'svg_parsers/index'

  namespace :api do
    namespace :v1 do
      get 'patterns/list'
      get 'patterns/get'

      get 'blocks/get'
      get 'blocks/list'
    end
  end
  root 'quilts#welcome'

end

app/views/shared/_progress.html.erb
<div id="top-of-view" class="progress-bar
  <%= 'two' if page == 2 %>
  <%= 'three' if page == 3 %>
  <%= 'four' if page == 4 %>
  <%= 'five' if page == 5 %>">

  <hr class="progress-line line-2">
  <div class="progress-element <%= 'selected' if page == 1 %>">
    <%= link_to project_templates_choose_project_path(quilt_id: params[:quilt_id]) do %>
    <span class="<%= 'selected-text' if page == 1 %> circle one">
      <span class="progress-number">1</span>
    </span>
    <span class="<%= 'selected' if page == 1 %> progress-stage">Choose Project</span>
    <% end %>
  </div>


  <div class="progress-element <%= 'selected' if page == 2 %>">
    <%= link_to quilts_choose_block_path(project_id: params[:project_id]) do %>
    <span class="<%= 'selected-text' if page == 2 %> circle two">
      <span class="progress-number">2</span>
    </span>
    <span class="<%= 'selected' if page == 2 %> progress-stage">Choose Block</span>
    <% end %>
  </div>

  <div class="progress-element <%= 'selected' if page == 3 %>">
    <%= link_to quilts_edit_project_path(quilt_id: params[:quilt_id], project_id: params[:project_id], block_id: params[:block_id]) do %>
    <span class="<%= 'selected-text' if page == 3 %> circle three">
      <span class="progress-number">3</span>
    </span>
    <span class="<%= 'selected' if page == 3 %> progress-stage">Design Block</span>
    <% end %>
  </div>

  <div class="progress-element <%= 'selected' if page == 4 %>">
    <%= link_to quilts_preview_project_path(quilt_id: params[:quilt_id]) do %>
    <span class="<%= 'selected-text' if page == 4 %> circle four">
      <span class="progress-number">4</span>
    </span>
    <span class="<%= 'selected' if page == 4 %> progress-stage">Preview Project</span>
    <% end %>
  </div>

  <div class="progress-element five <%= 'selected' if page == 5 %>">
    <span class="<%= 'selected-text' if page == 5 %> circle five">
      <span class="progress-number">5</span>
    </span>
    <span class="<%= 'selected' if page == 5 %> progress-stage">Next Steps</span>
  </div>

</div>